[package]
name = "chapter14cargo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A fun game where you guess what number the computer has chosen."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
